### PR TITLE
Improve font-lock-settings for elixir-ts-mode

### LINKED ISSUE #35: Rework fontification
This should resolve some open issues, so merging them into one. 

Related issues: 

- https://github.com/wkirschbaum/elixir-ts-mode/issues/33
- https://github.com/wkirschbaum/elixir-ts-mode/issues/32
- https://github.com/wkirschbaum/elixir-ts-mode/issues/30
- https://github.com/wkirschbaum/elixir-ts-mode/issues/23

### PR DESCRIPTION
**Pull request by wkirschbaum**
Fixes https://github.com/wkirschbaum/elixir-ts-mode/issues/35

### CODE REVIEW

**Comment by scohen** [comment]
This is a massive improvement, and it looks fantastic. 
❤️ 💜 💚 💙 💛

**Comment by scohen** [comment]
I found a small issue:

in function captures for local functions, the name of the function is given `font-lock-variable-name-face`, but it should receive `font-lock-function-call-face`

example:
```elixir
|> Stream.map(&normalize_token/1)
```
`normalize_token` is given `font-lock-variable-name-face`.

**Comment by wkirschbaum** [comment]
@scohen yes, i can see. will fix. I am sure there will be a few small fixes like this.

**Comment by wkirschbaum** [comment]
@scohen it should be fixed now if you don't mind testing. I also added the keyword-key face. I will run this for a day or two to spot issues and then push to melpa.

**Pull request merged**
